on:
  push:
    branches:
      - main
name: Build
jobs:
  build-binary:
    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-musl
          - build: macos-x86
            os: macos-latest
            rust: stable
            target: x86_64-apple-darwin
          - build: macos-silicon
            os: macos-latest
            rust: stable
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - name: Add target
        run: rustup target add ${{ matrix.target }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
