on:
  push:
    branches:
      - main
name: Build
jobs:
  build-binary:
    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-gnu
          - build: macos-x86
            os: macos-latest
            rust: stable
            target: x86_64-apple-darwin
          - build: macos-silicon
            os: macos-latest
            rust: stable
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - name: Add target
        run: rustup target add ${{ matrix.target }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Package artifacts
        run: |
          src=$(pwd)
          stage=
          case $RUNNER_OS in
              Linux)
                  stage=$(mktemp -d)
                  ;;
              macOS)
                  stage=$(mktemp -d -t tmp)
                  ;;
          esac
          cp target/${{ matrix.target }}/release/jolt-node $stage/
          cd $stage
          RELEASE_VERSION=${GITHUB_REF#refs/tags/}
          ASSET_NAME="jolt-node-$RELEASE_VERSION-${{ matrix.target }}.tar.gz"
          ASSET_PATH="$src/$ASSET_NAME"
          echo "ASSET_PATH=$ASSET_PATH" >> $GITHUB_ENV
          tar czf $ASSET_PATH *
          cd $src
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.ASSET_PATH }}
            ${{ env.CHECKSUM_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
